---
title: "National Parks"
author: "Evan Canfield"
date: "6/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Library Calls
```{r library calls, message=FALSE, warning=FALSE}
if (!require(tidyverse)) {install.packages('tidyverse')} 
library(tidyverse)
if (!require(readr)) {install.packages('readr')} 
library(readr)
if (!require(stringr)) {install.packages('stringr')} 
library(stringr)
if (!require(data.table)) {install.packages('data.table')} 
library(data.table)
if (!require(broom)) {install.packages('broom')} 
library(broom)
if (!require(plotly)) {install.packages('plotly')} 
library(plotly)
if (!require(ggthemes)) {install.packages('ggthemes')} 
library(ggthemes)
if (!require(RColorBrewer)) {install.packages('RColorBrewer')} 
library(RColorBrewer)
```

#Data Import / Export
```{r data import,  message=FALSE,}
#Visitation Data
nps_summary_complete<- read.csv("./data/annual_summary_report_1904-2018.csv", stringsAsFactors = FALSE)

#Location and Region Data on the Parks
list_np_locations <- read.csv(file = "./data/list_national_parks_location.csv", stringsAsFactors = F)
```

#Data Inspection
```{r}
glimpse(nps_summary_complete)

nps_rec_visits_all <- nps_summary_complete %>% 
  select(ParkName, Year, RecreationVisitors)

glimpse(nps_rec_visits_all)
```

#Reduce to National Parks
```{r}
#Add NP to American Samoa for FOllowing Filters
nps_rec_visits_all$ParkName <- str_replace_all(nps_rec_visits_all$ParkName, "National Park of American Samoa", "National Park of American Samoa NP")

nps_rec_visits_all %>% 
  distinct(ParkName)

nps_rec_visits_np <- nps_rec_visits_all %>% 
  filter(str_detect(string = ParkName, " NP")) %>% 
  filter(str_detect(string = ParkName, " NPRES") == FALSE)

nps_rec_visits_np %>% 
  distinct(ParkName)

glimpse(nps_rec_visits_np)

#Join Location Data
nps_rec_visits_np <- nps_rec_visits_np %>% 
  left_join(y = list_np_locations, by = c("ParkName"))

glimpse(nps_rec_visits_np)

```

#Line Graph
```{r}
l <- ggplot(data = nps_rec_visits_np, 
            mapping = aes(x = Year, y = RecreationVisitors, color = ParkName)) +
  geom_line() +
  guides(color = FALSE)

ggplotly(l)
```

#Identify Top 10
```{r}
glimpse(nps_rec_visits_np)

year_filter = 1800

nps_top_10 <- nps_rec_visits_np %>% 
  filter(Year >= year_filter) %>% 
  group_by(Year) %>%
  mutate(total_parks = n_distinct(ParkName)) %>% 
  mutate(visitors_rank = rank(RecreationVisitors)) %>% 
  mutate(np_rank = as.integer(total_parks - visitors_rank + 1)) %>% 
  ungroup() %>% 
  select(ParkName, np_id, np_rank) %>% 
  filter(np_rank <= 10) %>% 
  distinct(ParkName, np_id)

nps_top_10

```
#Line Graph Top 10
```{r}
nps_rec_visits_np_top_10 <- nps_rec_visits_np %>% 
  semi_join(y = nps_top_10, by = c("np_id"))

nps_rec_visits_np_top_10

l <- ggplot(data = nps_rec_visits_np_top_10, 
            mapping = aes(x = Year, y = RecreationVisitors, color = ParkName)) +
  geom_line() +
  theme_minimal()

ggplotly(l) %>% 
  layout(legend = list(x = 0.05, y = 0.99))
```


#Circular Bar Chart - R Grpah Gallery 295 - Data Prep
```{r}
#Filter for 2018
nps_rec_visits_np_2018 <- nps_rec_visits_np %>% 
  filter(Year == 2018)

#Filter Down to Only Park Name
nps_rec_visits_np_2018$ParkName <- str_remove_all(nps_rec_visits_np_2018$ParkName," NP")

glimpse(nps_rec_visits_np_2018)

nps_rec_visits_np_2018$ParkName <- str_remove_all(nps_rec_visits_np_2018$ParkName," & PRES")

glimpse(nps_rec_visits_np_2018)

#Filter Out Wolf Trap
nps_rec_visits_np_2018 <- nps_rec_visits_np_2018 %>% 
  filter(ParkName != 'Wolf Trap for the Performing Arts')

nps_rec_visits_np_2018 <- nps_rec_visits_np_2018 %>% 
  mutate(percent_visit = round(RecreationVisitors/sum(RecreationVisitors)*100,digits = 2))

glimpse(nps_rec_visits_np_2018)

nps_rec_visits_np_2018 %>% 
  arrange(np_id)
```

#Circular Bar Chart - R Grpah Gallery 295
```{r}
p_295 <-  
  ggplot(data = nps_rec_visits_np_2018, 
          mapping = aes(x = as.factor(np_id), y = percent_visit)) +
  geom_bar(stat = "identity", fill = alpha("blue", 0.3)) +
  ylim(-5, 13.5) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-2,4), "cm")     # This remove unnecessary margin around plot
  ) +
  coord_polar(start = 0)

p_295
```

#Circular Bar Chart With Labels - R Grpah Gallery 296
```{r}
labels <- nps_rec_visits_np_2018
 
# calculate the ANGLE of the labels
number_of_bar <- nrow(labels)

angle <- 90 - 360 * (labels$np_id - 0.5) / number_of_bar     

# I substract 0.5 because the letter must have the angle of the center of the bars. 
#Not extreme right(1) or extreme left (0)
 
# calculate the alignment of labels: right or left
# If I am on the left part of the plot, my labels have currently an angle < -90
labels$hjust <- ifelse( angle < -90, 1, 0)
 
# flip angle BY to make them readable
labels$angle <- ifelse(angle < -90, angle + 180, angle)

#plot
p_296 <-  
  ggplot(data = nps_rec_visits_np_2018, 
          mapping = aes(x = as.factor(np_id), 
                        y = percent_visit)) +
  geom_bar(stat = "identity", fill = alpha("blue", 0.3)) +
  ylim(-3, 13.8) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm")     # This remove unnecessary margin around plot
  ) +
  coord_polar(start = 0) +
  geom_text(data = labels, 
            mapping = aes(x = np_id, 
                          y = percent_visit + 0.5, 
                          label = ParkName,
                          hjust = hjust), 
            color="black", 
            fontface="bold", 
            alpha=0.6, 
            size=2, 
            angle= labels$angle, 
            inherit.aes = FALSE)

p_296
```

